# EDA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("../data/virat_odi_data.csv")

In [15]:
df

,Runs,Mins,BF,4s,6s,SR,Pos,Dismissal,Inns,Opposition,Ground,Start Date
0,12,33,22,1,0,54.54,2,lbw,1,v Sri Lanka,Dambulla,18 Aug 2008
1,37,82,67,6,0,55.22,2,caught,2,v Sri Lanka,Dambulla,20 Aug 2008
2,25,40,38,4,0,65.78,1,run out,1,v Sri Lanka,Colombo (RPS),24 Aug 2008
3,54,87,66,7,0,81.81,1,bowled,1,v Sri Lanka,Colombo (RPS),27 Aug 2008
4,31,45,46,3,1,67.39,1,lbw,2,v Sri Lanka,Colombo (RPS),29 Aug 2008
...,...,...,...,...,...,...,...,...,...,...,...,...
306,102,143,93,7,2,109.67,3,caught,1,v South Africa,Raipur,3 Dec 2025
307,65*,57,45,6,3,144.44,3,not out,2,v South Africa,Visakhapatnam,6 Dec 2025
308,93,123,91,8,1,102.19,3,caught,2,v New Zealand,Vadodara,11 Jan 2026
309,23,43,29,2,0,79.31,3,bowled,1,v New Zealand,Rajkot,14 Jan 2026
310,124,174,108,10,3,114.81,3,caught,2,v New Zealand,Indore,18 Jan 2026

In [4]:
df.shape

(311, 12)

In [5]:
df.describe()

,Runs,Mins,BF,4s,6s,SR,Pos,Dismissal,Inns,Opposition,Ground,Start Date
count,311,311,311,311,311,311,311,311,311,311,311,311
unique,153,144,117,22,9,219,8,8,3,14,69,311
top,0,-,-,0,0,0,3,caught,2,v Sri Lanka,Mirpur,18 Aug 2008
freq,18,49,12,58,207,17,244,178,171,56,16,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Runs        311 non-null    str
 1   Mins        311 non-null    str
 2   BF          311 non-null    str
 3   4s          311 non-null    str
 4   6s          311 non-null    str
 5   SR          311 non-null    str
 6   Pos         311 non-null    str
 7   Dismissal   311 non-null    str
 8   Inns        311 non-null    str
 9   Opposition  311 non-null    str
 10  Ground      311 non-null    str
 11  Start Date  311 non-null    str
dtypes: str(12)
memory usage: 29.3 KB

In [8]:
df.isnull().sum()

Runs          0
Mins          0
BF            0
4s            0
6s            0
SR            0
Pos           0
Dismissal     0
Inns          0
Opposition    0
Ground        0
Start Date    0
dtype: int64

In [9]:
df.columns

Index(['Runs', 'Mins', 'BF', '4s', '6s', 'SR', 'Pos', 'Dismissal', 'Inns',
       'Opposition', 'Ground', 'Start Date'],
      dtype='str')

In [18]:
df['Runs'].value_counts().sort_values(ascending=False)

Runs
0      18
2       8
DNB     8
31      7
9       7
       ..
74*     1
135     1
65*     1
93      1
124     1
Name: count, Length: 153, dtype: int64

In [29]:
df = df[~df['Runs'].isin(['DNB','TDNB'])]

In [30]:
df.shape

(299, 12)